// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ModMonBooks.Books.Api.Data.Migrations
{
	[DbContext(typeof(BooksDbContext))]
    [Migration("20240320153420_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("books")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModMonBooks.Books.Api.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books", "books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7d8f1d8-e136-49cf-817f-2d7bfe5f2bc2"),
                            Author = "Donald Knuth",
                            Isbn = "978-0-306-40615-7",
                            Price = 24.99m,
                            Title = "The Art of Computer Programming"
                        },
                        new
                        {
                            Id = new Guid("022c638f-105f-42aa-9594-ffdd29def50b"),
                            Author = "Michael Sipser",
                            Isbn = "978-0-201-89683-4",
                            Price = 32.99m,
                            Title = "Introduction to the Theory of Computation"
                        },
                        new
                        {
                            Id = new Guid("540adc5c-67b6-4d99-b484-312d26b80914"),
                            Author = "Thomas H. Cormen",
                            Isbn = "978-0-262-03384-8",
                            Price = 59.77m,
                            Title = "Introduction to Algorithms"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
